[package]
name = "rpgtools"
version = "0.2.0-alpha"
authors = ["Aaron Seilis <aaron.seilis@seilis.ca>"]
edition = "2018"
description = "Collection of utilities to help run tabletop role-playing games"
repository = "https://github.com/seilis/rpg-tools"
readme = "README.md"
keywords = ["rpg", "rpg-tool", "role-playing-game", "tabletop-rpgs"]
categories = ["games"]
license-file = "LICENSE"

[dependencies]
clap = "2.32"
rand = "0.6"
image = "0.21"

[[bin]]
name = "rpgmap"
path = "src/rpgmap.rs"

[lib]
name = "rpgtools"
path = "rpgtools/gridmap.rs"
