[package]
name = "rpgtools"
version = "1.1.0"
authors = ["Aaron Seilis <aaron.seilis@seilis.ca>"]
edition = "2018"
description = "Collection of utilities to help run tabletop role-playing games"
repository = "https://github.com/seilis/rpg-tools"
readme = "README.md"
keywords = ["rpg", "rpg-tool", "role-playing-game", "tabletop-rpgs"]
categories = ["games"]
license = "GPL-3.0"

[dependencies]
clap = "^2.33"
image = "^0.23.14"
itertools = "^0.8.0"
rand = "^0.8.3"

[[bin]]
name = "rpgmap"
path = "src/bin/rpgmap.rs"

[lib]
name = "rpgtools"
path = "src/rpgtools/lib.rs"
