[package]
name = "rpgtools"
version = "1.2.0"
authors = ["Aaron Seilis <aaron.seilis@seilis.ca>"]
edition = "2018"
description = "Collection of utilities to help run tabletop role-playing games"
repository = "https://github.com/seilis/rpg-tools"
readme = "README.md"
keywords = ["rpg", "rpg-tool", "role-playing-game", "tabletop-rpgs"]
categories = ["games"]
license = "GPL-3.0"

[dependencies]
clap = "^3.2.8"
image = "^0.24.2"
itertools = "^0.10"
rand = "^0.8"
resvg = "^0.23.0"
tiny-skia = "^0.6.6"
usvg = "^0.23.0"

[[bin]]
name = "rpgmap"
path = "src/bin/rpgmap.rs"

[lib]
name = "rpgtools"
path = "src/rpgtools/lib.rs"
