[package]
name = "rpgmap"
version = "0.0.1-alpha"
authors = ["Aaron Seilis <aaron.seilis@seilis.ca>"]

[dependencies]
clap = "2.32"
rand = "0.4"
image = "0.18.0"

[[bin]]
name = "rpgmap"
path = "src/rpgmap.rs"

[lib]
name = "rpgtools"
path = "rpgtools/gridmap.rs"
